# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Release major"
  lane :major do
	increment_build_number
	increment_version_number(
  		bump_type: "major"
	)
  end

  desc "Release minor"
  lane :minor do
	increment_build_number
	increment_version_number(
  		bump_type: "minor"
	)  end

  desc "Release patch"
  lane :patch do
	increment_build_number
	increment_version_number
  end

  desc "Release patch"
  lane :build do
	increment_build_number
  end
end
